#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 16, 2020 02:36:08 AM IST  platform: Linux

import sys
import os,subprocess
from subprocess import check_output
import PIL.Image, PIL.ImageTk

try:
	import Tkinter as tk
except ImportError:
	import tkinter as tk

try:
	import ttk
	py3 = False
except ImportError:
	import tkinter.ttk as ttk
	py3 = True

def set_Tk_var():
	global che48
	che48 = tk.IntVar()

def disable_enable_button():
	#w.Altitude.configure(text='''40.2''')
	w.EmStopButton.configure(state='normal' if che48.get() else 'disable')
	w.CallbackButton.configure(state='normal' if che48.get() else 'disable')

def init(top, gui, *args, **kwargs):
	global w, top_level, root
	w = gui
	top_level = top
	root = top

def create_grid(event=None):
    wid = 2000 # Get current width of canvas
    hei = 2000 # Get current height of canvas
    w.XYPositionalData.delete('grid_line') # Will only remove the grid_line

    # Creates all vertical lines at intevals of 100
    for i in range(0, wid, 100):
        w.XYPositionalData.create_line([(i, 0), (i, hei)], tag='grid_line')

    # Creates all horizontal lines at intevals of 100
    for i in range(0, hei, 100):
        w.XYPositionalData.create_line([(0, i), (wid, i)], tag='grid_line')

def dmode():
	

	if(w.colorflag == 0):
		col1= "#333333"#dark
		col2= "#ffffff"
		col3= "#000000"
		logo= "/home/walst/catkin_ws/src/shravas/scripts/gui/logodark.png"
		about= "/home/walst/catkin_ws/src/shravas/scripts/gui/about-dark.png"
		credits= "/home/walst/catkin_ws/src/shravas/scripts/gui/credits-dark.png"
		gridcol= "#4a4a4a"
		fbarcol,bbarcol="red","#4a4a4a"
		fsccol,bsccol="red","#4a4a4a"
		w.colorflag=1
	elif(w.colorflag == 1):
		col1= "#d9d9d9"#light
		col2= "#000000"
		col3= "#ffffff"
		logo= "/home/walst/catkin_ws/src/shravas/scripts/gui/logoba.jpeg"
		about= "/home/walst/catkin_ws/src/shravas/scripts/gui/about.png"
		credits= "/home/walst/catkin_ws/src/shravas/scripts/gui/credits.png"
		gridcol= "#ffffff"
		fbarcol,bbarcol="red","#d9d9d9"
		fsccol,bsccol="red","#d9d9d9"
		w.colorflag=0
			
	root.configure(bg=col1)
	w.style.configure('.',background=col1)
	w.style.configure('.',foreground=col2)
	w.style.configure('Horizontal.TProgressbar',foreground=fbarcol, background=fbarcol,troughcolor=bbarcol)
	w.style.configure('Horizontal.TScale',foreground=fsccol, background=fbarcol,troughcolor=bsccol)
	w.style.map('.', background=[('selected', col1), ('active',col1)])
	w.Logo.configure(background=col1 , foreground=col2)
	w.StatusLabel.configure(background=col1 , foreground=col2) 
	w.Status.configure(background=col1)
	w.BatteryLabel.configure(background=col1 , foreground=col2)
	#w.Battery.configure(background=col1 , foreground=col2)
	w.WifiLabel.configure(background=col1 , foreground=col2)
	#w.Battery.configure(background=col1 , foreground=col2)
	#w.AlitutdeBar.configure(background=col1 , foreground=col2)
	#w.SpeedBar.configure(background=col1 , foreground=col2)
	w.AltitudeLabel.configure(background=col1 , foreground=col2)
	w.SpeedLabel.configure(background=col1 , foreground=col2)
	w.ModeLabel.configure(background=col1 , foreground=col2)
	w.Mode.configure(background=col1 , foreground=col2)
	w.Wifi.configure(background=col1 , foreground=col2)
	w.Altitude.configure(background=col1 , foreground=col2)
	w.Speed.configure(background=col1 , foreground=col2)

	w.XYPositionalData.configure(background=gridcol)
	w.DroneLiveFeed.configure(background=col1)


	w.vsb.configure(bg=col1,activebackground=col1, highlightcolor=col1)


	ph = PIL.ImageTk.PhotoImage(PIL.Image.open(logo).resize((200, 50), PIL.Image.ANTIALIAS))
	w.Logo.configure(image = ph)
	w.Logo.image = ph

	ph = PIL.ImageTk.PhotoImage(PIL.Image.open(about).resize((857, 408), PIL.Image.ANTIALIAS))
	w.AboutSlide.configure(image = ph)
	w.AboutSlide.image = ph

	ph = PIL.ImageTk.PhotoImage(PIL.Image.open(credits).resize((857, 408), PIL.Image.ANTIALIAS))
	w.CreditsSlide.configure(image = ph)
	w.CreditsSlide.image = ph
	
	w.Error.configure(background=col1)
	w.Error.configure(foreground=col1)
	w.ConnectButton.configure(background=col1)
	w.ConnectButton.configure(foreground=col2)

	w.ConnectButton.configure(activebackground=col3)
	w.ConnectButton.configure(activeforeground=col2)

	w.CallbackButton.configure(background=col1)
	w.CallbackButton.configure(foreground=col2)
	w.CallbackButton.configure(activebackground=col3)
	w.CallbackButton.configure(activeforeground=col2)
	w.dmodeButton.configure(background=col1)
	w.dmodeButton.configure(foreground=col2)
	#w.ConnectButton.configure(activebackground=col3)
	#w.ConnectButton.configure(activeforeground=col2)
	w.EmLock.configure(background=col1)
	w.EmLock.configure(activebackground=col1)
	
	w.DeliveryDetailsPage.configure(background=col1)
	w.DroneFlightDataPage.configure(background=col1)
	w.AboutPage.configure(background=col1)
	w.CreditsPage.configure(background=col1)
	w.style.configure('TNotebook.Tab', background=col1)
	w.style.configure('TNotebook.Tab', foreground=col2)
	w.style.map('TNotebook.Tab', background=[('selected', col1), ('active',col1)])

	w.DeliveryList.configure(background=col3)
	w.DeliveryList.configure(foreground=col2)

	w.DeliveryDetails.configure(background=col3)
	w.DeliveryDetails.configure(foreground=col2)

	w.mvo.configure(background=col3)
	w.mvo.configure(foreground=col2)

	w.imu.configure(background=col3)
	w.imu.configure(foreground=col2)

	w.TelloEvents.configure(background=col3)
	w.TelloEvents.configure(foreground=col2)

	w.FlightData.configure(background=col3)
	w.FlightData.configure(foreground=col2)




def chk_conn():
		scanoutput = check_output(["iwlist", "wlp2s0", "scan"])
		ssid = "WiFi not found"
		for line in scanoutput.split():
		  line = line.decode("utf-8")
		  if line[:5]  == "ESSID":
			ssid = line.split('"')[1]

		if(ssid=="rn7p"):
			w.Status.configure(text='''Connected''', foreground="#2cbc00")
			w.ConnectButton.place_forget()
		else:
			w.ConnectButton.place(relx=0.886, rely=0.019, height=28, width=189)
			w.Status.configure(text="Disconnected",foreground="#ff0000")
			w.Error.configure(foreground="#ff0000")

def conn():
	if(os.system("nmcli device wifi connect QuadDrop password qwertyuiop")==0):
		w.ConnectButton.place_forget()
		w.Status.configure(text="Connected",foreground="#2cbc00")
		w.Error.place_forget()
	else:
		w.ConnectButton.place(relx=0.886, rely=0.019, height=28, width=189)
		w.Status.configure(text="Disconnected",foreground="#ff0000")
		w.Error.configure(foreground="#ff0000")

def destroy_window():
	# Function which closes the window.
	global top_level
	top_level.destroy()
	top_level = None

if __name__ == '__main__':
	import QuadDrop
	QuadDrop.vp_start_gui()
	




